### ISSUE TITLE
README generation specifies incorrect execution command

### ISSUE THREAD

**Issue by wpkelso** [ellie-commons/app-generator#20]
When the readme is generated, the standalone instance of the execution command appears to have fallen back to a generic or unspecified value, but generates correctly in the pasteable command text

![image](https://github.com/user-attachments/assets/d6216165-2b4f-4e42-b329-e37d66bb4f79)

**Comment by alainm23** [comment]
Fixed https://github.com/ellie-commons/elementary-app-template/commit/bf782aa2dd38cf55b2f53c8cab95e492290af40f
